### ISSUE TITLE
Missing File?

### ISSUE THREAD

**Issue by thxrben** [Matthias69/Onkyo-AVR-Control#1]
Hello 
I forked your project and wanted to experiment with it, but as soon as i started it i got a "NullPointException", because the File "gui/fxml/mainFrame.fxml" is missing.

Where can i get that from? It was not included in your Project as far as i see it...

Thanks :)

**Comment by MatthiasKuehne** [comment]
Hey!

The file is located in the `resources` folder (https://github.com/MatthiasKuehne/Onkyo-AVR-Control/blob/master/src/main/resources/gui/fxml/mainFrame.fxml).

Be sure to include its content in the build path.

Best regards
Matthias
